### ISSUE TITLE
Enhance "created" log in user role history table

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/geh-post-office#1008]
### Synopsis

Currently the "created" log in user role history table contains limited information (see screenshot 👇)

![image.png](https://images.zenhubusercontent.com/612cb8944df0eb85278b93db/13055781-cb3e-4042-bed8-edaaf853b3f9)

The log should be expanded to include information about role's name, description, status and permissions at the time of creation. 

Question: Should "EIC function" be included as well? Can "EIC function" be edited after creation?
_____________
### Acceptance Criteria
- [ ] The user should be able to see role's name, description, status and permissions at the time of creation
________________
### Tech. Notes
________________
### Task List
- [ ] UX mockup
- [ ] Front-end implementation
_________________
#### Tasks in Development
- [ ]
- [ ]
_________________

#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
- [ ] Verified by UX
