### ISSUE TITLE
Intern kommunikation: Som domænepostkontor vil jeg gerne kunne notificere postkontoret om dataavaliable

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#199]
As a domain post office user, I wish to notify the actual post office, when new data is available.

#### Accept criteria
- [x] A NuGet package containing DataAvailableNotification protobuf contract and API for sub domain communication
- [x] Internal post-office projects references the NuGet package instead of the project directly
- [x] XML documentation of NuGet package API and contracts
- [x] Update sub domain sample project to use the new NuGet package

# Tasks
- [x] Team meeting about nuget package structure.
- [x] Implement DataAvailableNotification Protobuf + DTO.
- [x] Implement "Send" API for submitting a DataAvailableNotification DTO.
- [x] Implement "Parse" API for reading a protobuf byte array into a DTO.
- [x] Make post-office use the new nuget package. (Mikkel)
- [x] Make sub-domain sample project use the new nuget package. (Karsten)
- [x] Document public API in nuget package. (Alex)
- [x] Test of: "Send" API, "Parse" API, post-office.
