### ISSUE TITLE
Intern kommunikation: Som domænepostkontor vil jeg gerne kunne modtage en kvittering fra postkontoret 'dequeued'

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#200]
As a domain post office user, I wish to be able to acknowledge a peeked message.

#### Accept criteria
- [x] A NuGet package containing Acknowledge protobuf contract and API for sub domain communication
- [x] Remove direct references to Acknowledge API and replace with NuGet package API
- [x] XML documentation of NuGet package API and contracts
- [x] Add Acknowledge functionality to sub domain sample project

# Tasks
- [x] Implement DequeuedNotification Protobuf + DTOs. (Jesper)
- [x] Implement "Send" API for submitting a DequeuedNotification DTO. (Jesper)
- [x] Implement "Parse" API for reading a protobuf byte array into a DTO. (Jesper)
- [x] Make post-office use the new nuget package. (Jesper)
- [x] Make sub-domain sample project use the new nuget package. (Jesper)
- [x] Document public API in nuget package.
- [x] Test of: "Send" API, "Parse" API, post-office. (Jesper)
