### ISSUE TITLE
Intern kommunikation: Som aktør vil jeg gerne kunne forespørge om data avaliable på en kø (peek). Resultat svar tilbage.

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#201]
As a domain post office user, I wish to be able to peek the next available message.

#### Accept criteria
- [x] A NuGet package containing Peek protobuf contract and API for sub domain communication
- [x] Remove direct references to Peek API and replace with NuGet package API
- [x] XML documentation of NuGet package API and contracts

# Tasks
- [x] Implement RequestMessage and DataSetReply Protobuf + DTOs. (Michael)
- [x] Implement "Send" API for submitting a RequestMessage DTO. (Michael)
- [x] Implement "Parse" API for reading a protobuf byte array into a DTO (for both RequestMessage and DataSetReply). (Michael)
- [x] Implement ResponseMessage DTO (Karsten)
- [x] Implement FailureReason DTO (Karsten)
- [x] Implement "Parse" ResponseMessage DTO (Karsten)
- [x] Implement "Send" ResponseMessage DTO (Karsten)
- [x] Make post-office use the new nuget package.
- [x] Make sub-domain sample project use the new nuget package. (Karsten)
- [x] Document public API in nuget package.
- [x] Test of: "Send" API, "Parse" API, post-office.
