### ISSUE TITLE
Logning: Fremsøgning af loggede meddelelser

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#205]
Som postkontor skal alle aktørkald audit-logges.

Problem Description
All communication in and out the Datahub must be logged including all messages in exact form.
This feature is refering to all outgoing communication including the peek and dequeue message

Benefit Hypothesis
In all cases it will be possible to find the basic data which has been the source to an activity in the DataHub

Acceptance criteria and must have scope
- [x] The traffic of all channels is logged. B2B and GUI
- [x] Exact message received and send is stored including rejected messages
- [ ] If feasible old messages (Older than 3 years) can be stored at cold storage
- [x] It must be possible to search for all messages independent of domains
- [x] Search criteria like message id, GLN etc (https://app.zenhub.com/files/337536836/29846062-4720-478e-94f8-f34a9d67b1c4/download)
- [x] Search function must work across all domains
- [x] Confirmation and rejection must be connected to the original message

##Objectives and key results
What is the revenue impact on our business? Is there a potential penalty or other adverse consequences if we delay?

Leading Indicators
What is the revenue impact on our business? Is there a potential penalty or other adverse consequences if we delay?

Non Functional Requirements
GDPR requirements are attached:
https://app.zenhub.com/files/337536836/c86c620b-b30f-4786-a6ea-8ff85c9e2094/download

Stakeholders
Relevant for all teams

Timeline
End of PI
