### ISSUE TITLE
Opret/redigere aktør på en org. (tilknytte/redigere markedsroller, netområder, målepunktstyper)

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#546]
- [x] På forsidelisten med aktører og organisationer, skal der være en knap til at oprette en ny aktør.
- [x] På forsidelisten med aktører og organisationer, skal der være en knap til at redigere en ny aktør.

Et skærmbillede til at oprette/redigere en ny aktør på en organisation.
- [x] Indtastning af GLN (kan ikke redigeres efter oprettelse).
- [x] Angivelse af Status.
- [x] Angivelse af et subset af alle markedsroller (mindst 1).
- [x] Der er nogle markedsroller, som ikke må overlappe. Rasmus vil have et regelsæt her.
- [x] Angivelse af et subset af alle netområder (mindst 1).
- [x] Angivelse af et subset af alle målepunktstyper (mindst 1).
- [ ] Efter oprettelse skal man kunne se ekstern aktørid også (ikke secret endnu, kræver mere afklaring).
- [x] Man skal kunne se fejlbeskeder fra backend, hvis oprettelsen fejler.
- [x] En Opret knap som danner aktøren og lukker skærmbilledet.
- [x] En Annuller knap som lukker skærmbilledet.

From meteringpointtypes task:
- [x] All these operations must be possible to do via a GUI
- [x] Any validation or error messages must be visible in the UI
