### ISSUE TITLE
Netområder - incl. GUI

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#557]
De manglende ting er overført til andre opgaver. Denne lukkes!

Acceptkriterier:
- [ ] Som DataHub GUI bruger vil jeg gerne kunne se en oversigt over Netområder med søgemuligheder i listen.
- [ ] Som DataHub FAS bruger vil jeg kunne se den samme oversigt samt at kunne editere i netområde navnet.
- [ ] Der skal være fremsøgningsmuligheder til stede
- [ ] Der skal være filtreringsmuligheder til stede
- [ ] Der skal være sorteringsmuligheder til stede.

Det forretningsmæssige krav/ønske er, at kunne danne sig et hurtigt overblik over detaljerne på et netområde.

På GUI fremsøg - skærmbilledet skal følgende knapper og data-felter være til stede:
- [ ] Netområde navn: rulleliste incl. smart søgning (delvis tekst = man kan søge på ’net’ og får alle hits op indeholdende ’net’)
- [ ] Netområde nr. : rulleliste incl. søgemulighed
- [ ] Netvirksomheds organisations ID: indtastningsfelt (til GLN/EIC)
- [ ] Aktiv: Flueben (ved markering fremsøges kun i aktive organisationer hvor 'end-date' ikke er opnået)
- [ ] Lup: Fremsøg
- [ ] Viskelæder: Rydder alle indtastninger i fremsøgningsfelterne. Note: Kan man nøjes med at lave ét søgefelt?

På selve liste resultat siden skal følgende knapper og data-felter være til stede:
- [ ] Netområde navn (tekst). Kan ved tryk sorteres i alfabetisk orden.
- [ ] Netområde nr. (3 tal). Nøgle. Default: Er sorteret i stigende orden. Clickable -> ny box åbner op med alle felter (herunder ekstra oplysninger). Til denne nye box er der en redigeringsblyant (til redigering af ’Netområdenavn’. Redigeringen skal logges/vises. 
- [ ] Netvirksomhed navn (tekst). Kan ved tryk sorteres i alfabetisk orden.
- [ ] Netvirksomheds ID (tal og bogstaver). Kan ved tryk sorteres i stigende orden.
- [ ] Prisområde: (enten DK1 eller DK2)
- [ ] Gyldig fra: (dato). XX-XX-XXXX
- [ ] Gyldig til: (dato). XX-XX-XXXX (kan være blank=aktivt netområde)
- [ ] Overgang til fuld flex: (dato) XX-XX-XXXX
- [ ] Nettabsmålepunkt (18 tal). MålepunktsID er clickable og man slår herefter målepunktet op (funktionen: ’Vis målepunkt’).
- [ ] Systemkorrektionsmålepunkt (18 tal). MålepunktsID er clickable og man slår herefter målepunktet op (funktionen: ’Vis målepunkt’).

- [ ] Som FAS bruger skal der endvidere være en redigeringsmulighed (det eneste felt, der skal kunne redigeres er 'Netområde navn'. 

- [ ] Teknisk Dokumentation
- [ ] Forretningsmæssig Dokumentation
- [ ] Integration events

https://www.figma.com/proto/4tVkjKm5fkIj61nx4XD3pA/DataHub-3.0?page-id=3724%3A49781&node-id=3748%3A50478&viewport=665%2C436%2C0.35&scaling=scale-down-width&starting-point-node-id=3748%3A50478

**Comment by Tm1807** [comment]
Se vedhæftet dokument

**Comment by Tm1807** [comment]
[https://app.zenhub.com/files/337536836/7d4718c7-0541-435f-9264-a2cead527839/download](https://app.zenhub.com/files/337536836/7d4718c7-0541-435f-9264-a2cead527839/download)
