### ISSUE TITLE
Opgave 2 - Implementering af markedsroller + UI

### ISSUE THREAD

**Issue by hsvig** [Energinet-DataHub/geh-post-office#597]
**Opgave**
Angivelse af et subset af alle markedsroller (mindst 1).
Der er nogle markedsroller, som ikke må overlappe. Rasmus vil have et regelsæt her.

**Tasks**
- [x] Mulighed for at vælge min. 1 EIC funktion via en dropdown.
- [x] Implementer validering af kombinationer af EIC funtioner (snak med Rasmus, han kender kombinationer @Rasmus)
 - - [x] Backend
 - - [x] Frontend

**Test**
Rasmus tester
 
**Accept kriterie:**
- [ ] Angivelse af et subset af alle markedsroller (mindst 1). Skal kunne vælges under oprettelse samt redigering af en aktør.

**Værdi ( hvad kan vi nu )**
- Det er nu muligt at oprette og redigere en aktør og tilknytte markedsroller.

**Comment by rasmus** [comment]
Det er vist den forkerte Rasmus 😀
