### ISSUE TITLE
Opgave 3 - Angivelse af netområde(r) til aktør + UI

### ISSUE THREAD

**Issue by hsvig** [Energinet-DataHub/geh-post-office#598]
**Opgave**
Angivelse af et subset af alle netområder (mindst 1).

**Tasks**
- [ ] Mulighed for at vælge min. 1 netområde via en dropdown.
- [ ] Snak med Rasmus om der er special validering iht. valg af netområde.

**Test**
Rasmus tester
 
**Accept kriterie:**
- [ ] Angivelse af et subset af alle netområder (mindst 1). Skal kunne vælges under oprettelse samt redigering af en aktør.

**Værdi ( hvad kan vi nu )**
- Det er nu muligt at oprette og redigere en aktør og tilknytte netområder.

**Comment by hsvig** [comment]
Bliver dækket af omskriving af koden
