### ISSUE TITLE
Opgave 5 - Angiv status for aktoer

### ISSUE THREAD

**Issue by hsvig** [Energinet-DataHub/geh-post-office#600]
**Opgave**
Som bruger skal jeg kunne angive status for en aktør under redigering. Når jeg opretter en ny aktør skal den automatisk oprettes med status "Ny".

**Tasks**
- [ ] Mulighed for at vælge en status via en dropdown under redigering.
- [ ] Validering af korrekt status transition.

**Test**
Rasmus tester
 
**Accept kriterie:**
- [ ] Aktør oprettes automatisk med status "Ny"
- [ ] Angivelse af aktørens status under redigering.

**Værdi ( hvad kan vi nu )**
- Det er nu muligt at oprette og redigere en aktør og angive status.
