### ISSUE TITLE
Netområde GUI - vis (ved klik på enkelt netområde)

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#687]
### Description
Som bruger vil jeg kunne se de detaljerede oplysninger
Vil vi kunne se en fremvisning af et specifikt netområde i dh3 ved klik på området i listevisningen.
Vi ønsker at se alle tilgængelige informationer på det specifikke netområde.

### Acceptance Criteria
**Header**
- [x] Netområde kode / netområde navn
- [x] netområde aktør / netområde markedsrolle / netområde aktør id

**Info**
- [x] Prisområde
- [x] gyldig til & gyldig fra
- [x] overgang til fuld flex
- [x] nettabsmålepunkt
- [x] systemkorrek. målepunk

![image.png](https://images.zenhubusercontent.com/60a604f0a6b94e63c1275443/4ba12a3d-54e3-4b89-b700-e897f24d0878)

Testing:
Rasmus tester at vist data stemmer overens med leveret data.

Demo:
Rasmus viser at det er muligt at åbne netområder fra listeside, og vise tilgængelige informationer.

DOD:
 Implementeringen af designet er godkendt af UX
 Data i listen stemmer overens med manuelt indtastet data i listesiden.

**Comment by Tm1807** [comment]
Nettab og systemkorrektionsmp overført til anden epic
