### ISSUE TITLE
Netområder - Basis listeside

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#691]
Som alle aktører i DH3
Vil vi kunne se en fremvisning af netområder i dh3
Vi ønsker en listevisning i brugergrænsefladen.
Så vi kan se hvilke net der er, og hvem der ejer dem. Vi kan alle relevante informationer omkring et netområde.

**prerequisites:**
- [x] [Design figma ](https://www.figma.com/proto/4tVkjKm5fkIj61nx4XD3pA/DataHub-3.0?page-id=3724%3A49781&node-id=3748%3A50478&viewport=665%2C436%2C0.35&scaling=scale-down-width&starting-point-node-id=3748%3A50478) er klar og godkendt.

**Note:**

Api til udtræk af data er en del af opgaven.

Listen bliver vist uden:
- sortering  ( implementeres i [#689](https://app.zenhub.com/workspaces/titans-60d029726fc7570010362aa7/issues/energinet-datahub/geh-post-office/689) ) 
- filtrering (implementeres i [#698](https://app.zenhub.com/workspaces/titans-60d029726fc7570010362aa7/issues/energinet-datahub/geh-post-office/698)) 
- Fremsøg (implementeres i [#699](https://app.zenhub.com/workspaces/titans-60d029726fc7570010362aa7/issues/energinet-datahub/geh-post-office/699) )

**Hvor bliver dette lavet nu ??????**
Api til indsendelse af data bliver lavet i?????

**Accept criterias:**

- [ ] Menu punkt til åbning af listeside

**Følgende data skal vises i listen:**
- [ ] Net-område nummer (ID)  (3 karakter alfanumerisk)
- [ ] Net-område navn (200 karakter alfanumerisk)
- [ ] Net-virksomheds navn (200 karakter alfanumerisk) Skal være oprettet i organisationer
- [ ] Net-virksomheds aktør ID (16 karakter alfanumerisk) Skal være oprettet i organisationer
- [ ] Prisområde (Skal være DK1 eller DK2)
- [ ] Gyldig fra dato
- [ ] Gyldig til dato

**Testing:**
Rasmus tester at vist data stemmer overens med leveret data.

**Demo:**
Rasmus viser at vist data stemmer overens med leveret data.
- [ ] Demo'et d. 02-09-2022 

### <b>DOD:</b>
- [x] Implementeringen af designet er godkendt af UX
- [ ] Data i listen stemmer overens med manuelt indtastet data. ( liste leveret til teamet )

![2022-08-22_13-33-28.png](https://images.zenhubusercontent.com/60bdc2fa67611ea75b0f57c0/d6aabe64-8ce9-490a-ae78-3c3c14d04112)

**Comment by Tm1807** [comment]
De resterende dele er splittet op i mindre opgaver. Denne lukkes derfor.
