### ISSUE TITLE
Netområde kode / netområde navn

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/geh-post-office#752]
### Acceptance Criteria

- [x] Netområde kode / netområde navn

### Testability
- [x] Can be demoed?
- [x] Can be tested?

### Optional Business Notes
- None

### Optional Techical Notes
- Includes flyout when opening item in overview list.

#### Tasks Completed

**Comment by ENDK-RHC** [comment]
Testet ok.
