### ISSUE TITLE
Correct permissions can see organisations.

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/geh-post-office#772]
### Acceptance Criteria

-  Only user with correct permissions can see organisations.

#### Testability
- [x] Can be tested?
- [x] Can be demoed?

### Optional Business Notes
- Changes to permission should happen within 1 hour.

### Optional Techical Notes
- TML has no permissions.
- RHC has full permissions.

### Task List

- [x] Add user property 'roles' + add user property to user flows.
- [x] Graph API, inside 'extension_roles' claim.

#### WebApi
- [x] Test that token is validated properly with MetadataAddress.
- [x] Update package to use roles instead of permissions.
- [x] Documentation.

#### UI
- [x] Create initial draft PR.
- [x] Add UTs to UI PR.
- [x] Documentation.

#### Azure AD
- [x] Create new Azure AD.
- [x] New U3 environment using Azure AD.

Texas Rangers Backlog for feature: https://app.zenhub.com/workspaces/mighty-ducks---texas-rangers-61941fea47ab810010e9aa91/issues/energinet-datahub/greenforce-frontend/600

**Comment by Tm1807** [comment]
Testet af Rasmus og Torben med succes.
