### ISSUE TITLE
Correct permissions can view organisations.

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/geh-post-office#774]
### Acceptance Criteria

- Only user with correct permissions can view organisations.

#### Testability
- [x] Can be tested?
- [x] Can be demoed?

### Optional Business Notes
- None

### Optional Techical Notes
- None

#### Tasks in Development
- [x] https://app.zenhub.com/workspaces/titans-60d029726fc7570010362aa7/issues/energinet-datahub/geh-post-office/919
- [x] Terraform configuration for u-002.

**Comment by Tm1807** [comment]
Testet af Rasmus og Torben med succes.
