### ISSUE TITLE
Correct permissions can create actors.

### ISSUE THREAD

**Issue by defectiveAi** [Energinet-DataHub/geh-post-office#777]
### Acceptance Criteria

- Only user with correct permissions can create actors.

#### Testability
- [x] Can be tested?
- [x] Can be demoed?

### Optional Business Notes
- RHC: See organizations, manage organizations, manage grid areas.
- TML: See organizations, manage actors.

### Optional Techical Notes
- None

#### Tasks in Development

- [x] Create initial Energinet actor.
- [x] Token-endpoint should return if current user is part of FAS.

**Comment by ENDK-RHC** [comment]
RHC can't manage actors. Test ok.
