### ISSUE TITLE
Som bruger skal man kunne se hvilken aktør/markedsrolle man er logget ind som

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#887]
### Synopsis
Som bruger ønsker jeg at kunne se hvilken  aktør/markedsrolle jeg er logget ind som i DataHub GUI

https://www.figma.com/file/fwEDQkgEcpwfUojXl0EIC5/Watt-Design-System?node-id=4779%3A12038&t=Pzclaz26h13fMTsC-1
___________
### Acceptance Criteria
- [x] Brugeralias/mailadresse/markedsaktørnavn/markedsrolle er vist på GUI på alle skærmbilleder
____________
### Tech. Notes
________________
### Task List
- [x] Backend: API som udstiller actors (GLN, navn) givet en liste af id'er (mjm)
- [x] Frontend: Gem valgte bruger i local storage. (mjm)
- [x] Frontend: Præsenter valgte bruger.
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?

**Comment by ENDK-RHC** [comment]
Har testet og det er muligt at se hvilken bruger man er logget ind som.
Test OK.
