### ISSUE TITLE
Som bruger skal man kunne skifte mellem de tildelte aktør/markedsroller

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#888]
### Synopsis
Som en bruger der er tilknyttet flere forskellige aktører/markedsroller
Skal jeg kunne skifte mellem disse aktører/markedsroller
For nemt (som bruger) at kunne håndtere flere forskellige aktører/markedsroller

https://www.figma.com/file/fwEDQkgEcpwfUojXl0EIC5/Watt-Design-System?node-id=4779%3A12038&t=Pzclaz26h13fMTsC-1
___________
### Acceptance Criteria
- [x] For en bruger med tilknytning til flere forskellige aktører/markedsroller kan der nemt skiftes mellem aktørerne/markedsrollerne (ingen krævet handling af brugeren omkring log-out/log-in)
- [x] En bruger, der skifter aktør/markedsrolle skal rolle/rettighedsopdateres uden 'front'-logout/login
____________
### Tech. Notes
One-off drop-up (ikke komponent)

________________
### Task List
- [x] Extend component with selection
- [x] Save selection in local storage
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
