### ISSUE TITLE
Liste over brugerroller

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#889]
### Synopsis
Som FAS brugeradmin skal jeg kunne se en liste over eksisterende brugerroller i DH GUI

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Akt%C3%B8rer-og-brugere%2C-roller-og-rettigheder?node-id=22%3A23423&t=AET9r5IIx5uXUuah-1

___________
### Acceptance Criteria
- [ ] Listen skal indeholde: Brugerrollenavn, Beskrivelse, tilhørende markedsrolle, status (aktiv/blokeret/inaktiv), 
____________
### Tech. Notes
Client side paging og søgning, da antallet af roller forventes at være 100-200
________________
### Task List
- [x] Frontend
- [x] Backend
  - [x] Tests

_________________
#### Testability
- [x] Can be tested?
- [x] Can be demoed?

**Comment by Tm1807** [comment]
*standard' bruger-roller til alle typer af markedsroller:
FAS
•	Adgang til CPR visning (alle målepunkter)
•	Brugeradministration
•	Admin til håndtering af aktørstamdata + systemparametre + evt håndtering af ekstramodtager
•	Afregningskørsler
•	HTX-rettelser
•	Se adgang
•	Rapporter - tværgående for alle aktører
 
 EZ (Det gamle SYO)
•	Adgang til oprettelse / ændring af tariffer
•	Adgang til at se og til tilknytning af tariffer
•	Se adgang - måske ikke relevant?
•	Forespørger vi på data til afregning?
•	Rapporter?
 
 DDM
•	Brugeradministration
•	Rapporter
•	Frontoffice - se adgang
•	Backoffice - ret til initiering af stamdataprocesser
•	Backoffice - ret til initiering af måledataprocesser / rykkere ? (MDR)
•	(HTX-rettelser i kladde)
 
 DDQ
•	Brugeradministration
•	Adgang til CPR visning
•	Rapporter
•	Sælger adgang (opslå målepunkter og se evt. akkumuleret forbrug på ny kunder, hvis det kan give mening og er lovligt)
•	Frontoffice - se adgang
•	Backoffice - ret til initiering af processer
•	(HTX-rettelser i kladde - elvarme til netvirksomhed)
 
 DDK
•	Brugeradministration
•	Se adgang (med mulighed for at forespørge på data via søg forretningsbesked)
•	Rapporter
 
 
MDR
•	Brugeradministration
•	Rapporter
 
CAS 
•	
 
DDX
•	 
 
 STS
•	Brugeradministration
•	Se adgang til lovpligtige opgaver
 
 DDZ (Den gamle DHB som modtager alle beskeder og generer afregningsgrundlag)
•	 
 
DGL ???
•

**Comment by ENDK-RHC** [comment]
RHC: Testet ok
