### ISSUE TITLE
Oprette en brugerrolle

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#890]
### Synopsis
Som FAS brugeradmin skal jeg kunne oprette en brugerroller i DH GUI

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Akt%C3%B8rer-og-brugere%2C-roller-og-rettigheder?node-id=22%3A24289&t=AET9r5IIx5uXUuah-1
___________
### Acceptance Criteria
- [ ] Rollen skal oprettes med navn, beskrivelse, status (aktiv, inaktiv) og hvilken markedsrolle den er gældende for.
____________
### Tech. Notes
________________
### Task List
- [x] Backend: API til oprettelse af brugerrolle
- [x] Frontend: Stamdata
- [x] Frontend: Tildel rettigheder
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?

**Comment by ENDK-RHC** [comment]
RHC har testet at der kan oprettes en brugerrolle. Test gennemført med OK resultat.
