### ISSUE TITLE
Fjernelse af roller fra brugere som FAS brugeradmin - historik

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#901]
### Synopsis
Som FAS brugeradmin ønsker jeg at kunne se en historik over ændringer ved fjernelse af roller
___________
### Acceptance Criteria
Historik skal vises ( med følgende info )
- [ ] Tildeling af rolle
- [ ] Sletning af rolle
- [ ] Hvem har gjort det
- [ ] Tidspunkt

____________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
