### ISSUE TITLE
Liste over brugerroller - filtrering

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#902]
### Synopsis
Som FAS brugeradmin skal jeg kunne se en liste over eksisterende brugerroller i DH GUI

Den måde filtrering er tegnet på i Figma, har vi ikke endnu. Filtrering kan laves ligesom på Fremsøg forretningsbesked. Alternativt kan filtrering placeres mellem tabs og listen, da det hierarkisk giver mere mening, men det er ikke så vigtigt nu, da vi meget gerne skulle have filtrering ind i card med listen på sigt. /PEC

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Akt%C3%B8rer-og-brugere%2C-roller-og-rettigheder?node-id=22%3A23423&t=AET9r5IIx5uXUuah-1
___________
### Acceptance Criteria
- [ ] Det skal være muligt at kunne filtrere i listen (markedsrolle, inaktiv/aktiv)
(info: der er pt en fejl i dropdown komponenten, som gør at man ikke kan vælge flere markedsroller når man søger i dropdown listen, det virker hvis man ikke søger i dropdown)
____________
###

________________
### Task List
- [ ]
- [ ]
_________________
#### Testability
- [x] Can be tested?
- [x] Can be demoed?

**Comment by ENDK-RHC** [comment]
RHC: Testet ok.
