### ISSUE TITLE
Liste over brugerroller - detaljer

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#903]
### Synopsis
Som FAS brugeradmin skal jeg ved klik på en rolle kunne se detaljer for brugerrollen (underliggende rettigheder)

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Akt%C3%B8rer-og-brugere%2C-roller-og-rettigheder?node-id=22%3A23813&t=AET9r5IIx5uXUuah-1
___________
### Acceptance Criteria
- [ ] Ved klik på en rolle skal man kunne se detaljer for brugerrollen (underliggende rettigheder)
____________
### Tech. Notes
Tab-komponent skal inkluderes i denne story
________________
### Task List
- [ ]
- [ ]
_________________
#### Testability
- [x] Can be tested?
- [x] Can be demoed?

**Comment by ENDK-RHC** [comment]
RHC: Testet ok.
