### ISSUE TITLE
Redigere en brugerrolle - historik

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#913]
### Synopsis
På rediger brugerrolle siden vil jeg kunne se en historik over ændringer.
___________
### Acceptance Criteria
- [ ] Hvem har gjort det
- [ ] Tidspunkt
____________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
