### ISSUE TITLE
[Titans] Enabler: Roller, Middleware mm.

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#919]
### Synopsis

- [x]  Frontend: Der skal sendes et kald til backend for at hente roller. Det skal indsættes et header elementer der viser hvilken aktør der er valgt.
  - [x] Fjerne scope service.
  - [x] Tilføje kald til at hente aktører for logget ind bruger gennem BFF, som returner en liste af aktører.
  - [x] Tilføje kald til at hente brugerrettigheder.
  - [x] Tilføje kald til /token gennem BFF, som returner en token.
  - [x] Send AJWT med alle API kald (HttpRequestInterceptor).

- [x] BFF: Valider begge tokens gennem middleware.

- [x] Domæne: Tilføj domænelogik.
  - [x] Brugertabel 1-* tabel med roller. (juj)
  - [x] Roller 1-* tabel med rettigheder (seed data). (juj)
  - [x] Brugertabel 1-* tabel med aktører. (juj)

- [x] MarketParticipant: Frontend skal kunne kalde et api hvor en liste af tilknyttet aktørere returneres.
  - [x] /token (anon)
  - [x] Get actors for given user (think about auth here!).
  - [x] Brug KV keys til signing med auto-rotation.
  - [x] Middleware skal opdateres, så vi validerer begge tokens, JWT og AJWT.

_____________
### Acceptance Criteria
- [ ]
- [ ]
________________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Tasks in Development
- [ ]
- [ ]
_________________

#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
