### ISSUE TITLE
 Søgning i Liste over brugere, der ønsker at få tildelt roller af FAS bruger admin

### ISSUE THREAD

**Issue by hsvig** [Energinet-DataHub/geh-post-office#922]
### Synopsis

Som FAS bruger ønsker jeg at kunne søge i listen over alle brugere for at kunne vælge en bruger.

- [ ] Der skal kunne søges i følgende felter: email, navn, telefonnummer, roller, aktørnavn, aktørGLN, aktørmarkedsrolle, oprettelsesdato, status (aktiv, inaktiv/blokeret)
_____________
### Acceptance Criteria
- [x] Søgning
________________
### Tech. Notes
- As long as we are on Azure B2C we cannot search on the following fields: mobilePhone
- Vi begrænser fritekst søgning til navn, email, telefonnr., GLN, aktørnavn. På et senere tidspunkt gør vi det muligt at filtrere på markedsrolle og status (evt. også brugerrolle)
________________
### Task List
- [x] Backend: Add search filters for our data (juj) (Done)
- [x] Frontend: Add search filters
- [x] Frontend: Add BFF controller for searching
_________________
#### Tasks in Development
- [ ]
- [ ]
_________________

#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
