### ISSUE TITLE
Filtrere i listen over brugere, der skal tildeles roller af FAS bruger admin

### ISSUE THREAD

**Issue by hsvig** [Energinet-DataHub/geh-post-office#923]
### Synopsis
Som FAS bruger ønsker jeg at kunne filtrere i listen over alle brugere for at kunne vælge en bruger.

- [x] Flueben aktiv/inaktiv
_____________
### Acceptance Criteria
- [ ]
- [ ]
________________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Tasks in Development
- [ ]
- [ ]
_________________

#### Testability
- [x] Can be tested?
- [x] Can be demoed?
