### ISSUE TITLE
[Titans] (Epic1) Create FAS user with role/rights FAS

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#951]
### Synopsis
Til Epic 1 skal der bruges en FAS bruger, der kan tilgå GUI med FAS-rettigheder

_____________
### Acceptance Criteria

- [ ] FAS-bruger
- [ ] Mulighed for at tilknytte rettigheder: Enable Fas user to view non-profiled consumption per energy supplier, balance responsible and grid area

### Noter
________________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
