### ISSUE TITLE
Udruldning i alle miljøer

### ISSUE THREAD

**Issue by Tm1807** [Energinet-DataHub/geh-post-office#952]
### Synopsis
_____________
### Acceptance Criteria
________________
### Tech. Notes
________________
### Task List
- [x] greenforce-frontend PR ready: https://github.com/Energinet-DataHub/greenforce-frontend/pull/1200
- [x] Frontend integration test user does not have permission yet in our DB, so E2E tests fail.
- [x] geh-infrastructure PR ready: https://github.com/Energinet-DataHub/dh3-infrastructure/pull/70
- [x] geh-wholesale PR ready: https://github.com/Energinet-DataHub/opengeh-wholesale/pull/563
- [x] geh-wholesale needs to make DomainTests work.
- [x] geh-market-participant PR ready: https://github.com/Energinet-DataHub/geh-market-participant/pull/324
- [x] geh-message-archive PR ready: https://github.com/Energinet-DataHub/geh-message-archive/pull/101
- [x] geh-charges PR ready: https://github.com/Energinet-DataHub/geh-charges/pull/1895
- [x] geh-metering-point. (Batman confirmed that the UI is allowed to break).
- [x] Update documentation: https://github.com/Energinet-DataHub/greenforce-art/pull/130
- [x] dh3-environment PR ready: https://github.com/Energinet-DataHub/dh3-environments/pull/336
- [x] Fix bug: https://app.zenhub.com/workspaces/titans-60d029726fc7570010362aa7/issues/energinet-datahub/geh-post-office/968
- [x] Merge it all.
_________________

#### Testability
- [x] Can be tested?
- [ ] Can be demoed?

**Comment by ENDK-RHC** [comment]
Har ikke rettigheder til at ændre i U002
Har rettigheder til at ændre i T001
Test ok.

**Comment by Tm1807** [comment]
Har rettigheder til at ændre organisationer, aktører og netområder i T001
Har ikke de tilsvarende muligheder i U002.
Test ok!
