### ISSUE TITLE
Undersøg hvilke WCAG der påvirker design

### ISSUE THREAD

**Issue by PernilleChristiansen** [Energinet-DataHub/geh-post-office#959]
#[https://app.zenhub.com/files/337536836/c5c0e617-455d-40c2-a024-0444c8414ba6/download](https://app.zenhub.com/files/337536836/c5c0e617-455d-40c2-a024-0444c8414ba6/download)## Synopsis
_____________
### Acceptance Criteria
- [ ] Liste over WCAG, der har indflydelse på design
- [ ]
________________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Tasks in Development
- [ ]
- [ ]
_________________

#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
