### ISSUE TITLE
Udvid brugerliste til tildeling af roller med mere bruger data fra Azure

### ISSUE THREAD

**Issue by michaelmajgaard** [Energinet-DataHub/geh-post-office#965]
### Synopsis

For at kunne tildele roller til en bruger, skal FAS brugeradmin have mulighed for at se brugers informationer i listen.
_____________
### Acceptance Criteria
- [x] Brugerlisten skal udvides med følgende elementer: navn, telefonnummer, oprettelsesdato, status (aktiv, inaktiv/blokeret)

### Noter
Søgning og filtrering er ikke en del af denne opgave.
________________
### Task List
- [x] Backend: Integrer med Azure med henblik på udtræk af brugerdata. (mjm)
- [x] Backend: Udvide den udstillede brugermodel med det nye data.
- [x] Frontend: Præsenter de nye brugerfelter i listen.
_________________
#### Testability
- [x] Can be tested?
- [x] Can be demoed?

https://www.figma.com/file/ajciTUjaaRt1sdgMnbtzCz/Akt%C3%B8rer-og-brugere%2C-roller-og-rettigheder?node-id=0%3A1&t=UE4MLaPq0X66OSXX-1

![image.png](https://images.zenhubusercontent.com/60bdc2fa67611ea75b0f57c0/7e24eab7-3cc2-46f3-8215-49e0487d2843)
