### ISSUE TITLE
Analyse af WCAG

### ISSUE THREAD

**Issue by PernilleChristiansen** [Energinet-DataHub/geh-post-office#967]
### Synopsis
_____________
### Acceptance Criteria
- [x] Dokumentation af, hvilke krav vi skal overholde
- [x] Forslag til metoder, der kan hjælpe os med at leve op til success kriterierne
- [ ] Forberede møde med Mogens

https://energinet.atlassian.net/wiki/spaces/D3/pages/285835265/WCAG+2.1
________________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Tasks in Development
- [ ]
- [ ]
_________________

#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
