### ISSUE TITLE
Opdater text styles I Figma

### ISSUE THREAD

**Issue by PernilleChristiansen** [Energinet-DataHub/geh-post-office#977]
### Synopsis

Opdater text styles i Figma
_____________
### Acceptance Criteria
- [ ] Text styles skal leve op til WCAG kriterier
- [ ]
________________
### Tech. Notes
________________
### Task List
- [ ]
- [ ]
_________________
#### Tasks in Development
- [ ]
- [ ]
_________________

#### Testability
- [ ] Can be tested?
- [ ] Can be demoed?
